### ISSUE TITLE
qbittorrent must not download if vpn fail

### ISSUE THREAD

**Issue by ochagnon** [UnblockApp/qbittorrent#10]
we noticed it still starts even if it couldn't connect to vpn

**Comment by bclermont** [comment]
@mogikanin ping 2 months timeout

**Comment by mogikanin** [comment]
i.e. it means when option 'Use secure VPN" is  checked, but no vpn connection by some reason, then we should not allow to download anything?

**Comment by bclermont** [comment]
> then we should not allow to download anything?

exactly, to make sure no leaking of torrent'ing
